run:
  timeout: 5m
  tests: true
  go: '1.24.0'

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - gosec
    - gocritic
    - gosimple
    - typecheck
    - bodyclose
    - nilerr
    - noctx

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
