run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - gosimple
    - unused
    - typecheck
    - bodyclose
    - nilerr
    - noctx

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
